spring:
  application:
    name: lived

  datasource:
    url: "${RDS_URL}"
    username: "${RDS_USERNAME}"
    password: "${RDS_PASSWORD}"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc.batch_size: 20
    open-in-view: false

logging:
    level:
      root: info
      com.lived: info




