spring:
  application:
    name: lived

  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: update # 엔티티 변경 시 DB 테이블을 자동 업데이트
    show-sql: true
    properties:
      hibernate:
        format_sql: true



